from . import college_student
from . import college_course
from . import college_admission
from . import college_semester
from . import college_subject
from . import college_class
from . import college_exam
from . import college_academic
from . import college_paper
from . import college_marksheet
from . import college_promotion
